spring.application.name=Cache36
server.port=9761
spring.datasource.url= jdbc:mysql://localhost:3306/db
spring.datasource.username= user
spring.datasource.password= password
spring.cache.type= redis
spring.redis.host= localhost
spring.redis.port=${PORT_REDIS}


