spring.application.name= Client0
server.port = 9010
proxy.base-url3 = http://Ambassador0:9011
proxy.base-url1 = http://Ambassador1:9013
proxy.base-url3 = http://Ambassador1:9013
proxy.base-url1 = http://Ambassador0:9011
