spring.application.name=Cache5
server.port=9342
spring.datasource.url= jdbc:mysql://localhost:3306/db
spring.datasource.username= user
spring.datasource.password= password
spring.cache.type= redis
spring.redis.host= localhost
spring.redis.port=${PORT_REDIS}


